export default {
  box: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-start',
    height: '0.13vw',
  },
  bd: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    flexDirection: 'row',
    opacity: '1.00',
    width: '0.00vw',
    height: '0.00vw',
  },
  layer: { position: 'absolute', top: '0.00vw', left: '0.00vw', width: '0.00vw', height: '0.00vw', overflow: 'hidden' },
  bg: { position: 'absolute', top: '0.00vw', left: '0.00vw', opacity: '1.00', width: '0.00vw', height: '0.00vw' },
  wrap: {
    boxSizing: 'border-box',
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: '0.00vw',
    marginLeft: '0.00vw',
    borderRadius: '0.00vw',
    backgroundColor: 'rgba(0,0,0,0.40)',
    paddingRight: '0.00vw',
    paddingLeft: '0.00vw',
    height: '0.00vw',
  },
  riverdinwei: { opacity: '1.00', width: '0.00vw', height: '0.00vw' },
  distance: {
    marginLeft: '0.00vw',
    height: '0.00vw',
    fontWeight: 400,
    fontSize: '0.00vw',
    color: '#ffffff',
    lineHeight: '0.00vw',
    whiteSpace: 'nowrap',
  },
  main: {
    display: 'flex',
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    width: '0.00vw',
    height: '0.00vw',
  },
  title: {
    marginTop: '0.00vw',
    width: '0.00vw',
    height: '0.00vw',
    fontWeight: 400,
    fontSize: '0.00vw',
    color: '#333333',
    lineHeight: '0.00vw',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  ft: {
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomLeftRadius: '0.00vw',
    borderBottomRightRadius: '0.00vw',
    backgroundColor: '#ffffff',
    paddingRight: '0.00vw',
    paddingLeft: '0.00vw',
    width: '0.00vw',
    height: '0.00vw',
    overflow: 'hidden',
  },
  block: { display: 'flex', alignItems: 'center', flexDirection: 'row', height: '0.00vw' },
  xianjin: { width: '0.00vw', height: '0.00vw' },
  fashionHome: {
    marginLeft: '0.00vw',
    height: '0.00vw',
    fontWeight: 300,
    fontSize: '0.00vw',
    color: '#666666',
    lineHeight: '0.00vw',
    whiteSpace: 'nowrap',
  },
  group: { display: 'flex', alignItems: 'center', flexDirection: 'row', height: '0.00vw' },
  favorite: { width: '0.00vw', height: '0.00vw' },
  num: {
    marginLeft: '0.00vw',
    height: '0.00vw',
    fontWeight: 400,
    fontSize: '0.00vw',
    color: '#999999',
    lineHeight: '0.00vw',
    whiteSpace: 'nowrap',
  },
};
